### ISSUE TITLE
Messari price source is unreliable

### ISSUE THREAD

**Issue by khand100** [CypherpunkPay/CypherpunkPay#13]
Hi,
I just want to inform you that I often see this stacktrace in my logs:
```
2022-01-07 13:24:13,931 ERROR Job "update_price_tickers" raised exception
 Traceback (most recent call last):
  File "/opt/venvs/cypherpunkpay/lib/python3.8/site-packages/cypherpunkpay/jobs/job.py", line 13, in __call__
    self.job()
  File "/opt/venvs/cypherpunkpay/lib/python3.8/site-packages/cypherpunkpay/jobs/job_adder.py", line 17, in <l>
    lambda: self._app.price_tickers().update(),
  File "/opt/venvs/cypherpunkpay/lib/python3.8/site-packages/cypherpunkpay/prices/price_tickers.py", line 54,>
    self.update_coin(coin)
  File "/opt/venvs/cypherpunkpay/lib/python3.8/site-packages/cypherpunkpay/prices/price_tickers.py", line 61,>
    MessariCoinPriceSource(self._http_client).get(coin, 'usd')
  File "/opt/venvs/cypherpunkpay/lib/python3.8/site-packages/cypherpunkpay/prices/messari_coin_price_source.p>
    return Decimal(parsed_json['data']['market_data']['price_usd'])
KeyError: 'data'
```

They probably respond with an error object which has no data key. Overall I think the price source http requests should check the response status code before assuming its json. Logging warnings with at least the http status code may also help in the future to detect no longer working price sources.

And since I mentioned logging 😃 Could you consider decreasing the stats logging interval for production environments?
10 seconds is rather spammy and the stats are not that important in the log in my opinion. More interesting are charge status changes or price source and callback errors.

**Comment by CypherpunkDev** [comment]
Thanks for reporting, will investigate.

**Comment by CypherpunkDev** [comment]
1) Do you still have issues with Messari price source? I gave it some time and it looks fine in my logs now (no Messari exceptions).

2) The HTTP status code is verified by underlying HTTP client and JSON parsing is skipped if not OK. This is intentionally not logged because temporary connection failures are very often over Tor. Instead, I myself verify price sources fairly reguraly by running network tests. I do give them a slack time before disabling though.

3) Regarding the interval I will consider decreasing it. My motivation for 10s was to evidence the daemon is live and healthy.

**Comment by khand100** [comment]
Indeed the last time I see it in the logs is 2022-01-08 01:27:13,129 maybe they just had problems for a couple of days.

The call to json will not check the http status code, it blindly tries to parse the body as json. See here [Response.json](https://docs.python-requests.org/en/latest/_modules/requests/models/#Response.json).
And [base_http_client.py#get_accepting_linkability](https://github.com/CypherpunkPay/CypherpunkPay/blob/master/cypherpunkpay/net/http_client/base_http_client.py#L31) also does not check the http status code.
You could add a call to requests [raise_for_status](https://docs.python-requests.org/en/latest/api/#requests.Response.raise_for_status) in get_accepting_linkability to change that. Then the traceback would have been silently swallowed by the try/except block in the messari price source.

But I am not really a fan of that, I would prefer a single log line with level warning and at least the status code.
Because I still assume they answered with a json error object and a non 200 status code, but without logging we will never know or notice.

What happens when all price sources silently fail? Will the last potential very out of date price be used or are there safeguards?

**Comment by CypherpunkDev** [comment]
You are correct regarding the status codes.

When all price sources fail then the last (potentially out of date) price will be used.

**Comment by CypherpunkDev** [comment]
Logging status codes >=400 is done.

**Comment by CypherpunkDev** [comment]
Protection against stale prices is done (awaiting deb release).

**Comment by khand100** [comment]
Looks good, thank you very much.

I also like the new theme, but in my opinion the colorful qrcode is too much. With just a black and white qrcode it looks better, but in the end it's a matter of taste.
And you should probably improve the readability of `a:hover` black is barely visible. Maybe switch to something white?

Do you maintain a changelog somewhere? Because reading commit messages is not possible for everyone. Maybe on the website or as github releases?
