### ISSUE TITLE
Lightning description is empty

### ISSUE THREAD

**Issue by rustyrussell** [CypherpunkPay/CypherpunkPay#14]
e.g donated $5 USD (weird that you don't support sats as a currency BTW!)

lnbc117220n1ps7pyz4pp5ejc2kj7l6e63x5apnm0p25t9rl9x8mqd4j4k3dmtztnxxxhm2e2qdqqcqzpgxqrp9ssp5rrwl7x523cppfc7up6ywsunazgg76p67llkvwgejzmqtr7nsjk2s9qyyssqhm946gz6s8zl8lzhejrmrh5mlnd3n7akeh6lfdaqcdkhzuwmhds9q24egrwwulakn62cus3ty782k0ed3dmpfsw4e00jcv3lfac8x7qqwe6pm7

Ideally I'd like to see the USD amount and URL on the description, so it's sane in my wallet?

**Comment by CypherpunkDev** [comment]
I fully agree on both. Thanks so much for taking time to test/donate! It means a ton for me.

**Comment by CypherpunkDev** [comment]
Both issues are now fixed in master (payment description and BTC/sats denomination). Official release soon.
