### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by 12nick12** [CypherpunkPay/CypherpunkPay#15]
No sure if this would be useful, but I would love the option to add an email field that way people have a receipt from when they donate or if they use low fees get alerted when the payment gets confirmed.

**Comment by CypherpunkDev** [comment]
Thanks a lot for your suggestion! I will think about it (or how to achieve similar goals) but some immediate concerns regarding email come to mind.

CypherpunkPay could optionally collect some contact details (like email or twitter handle) but it probably shouldn't on its own send out emails. It's not obvious but reliable email sending is infrastructure heavy and would make the software harder to install and configure. Using 3rd party mailing services like mailgun is easy but out of question for privacy reasons.

I need to give it more thought.

**Comment by 12nick12** [comment]
Ah ok, thank you for your response. I use AWS SES for everything. I understand your concern. I would add a disclaimer where people can input their email, but let it be known it might be used by 3rd parties, example sent email via AWS SES.

**Comment by CypherpunkDev** [comment]
While I agree it would be nice to receive some kind of asynchronous confirmation on a successful donation, at the moment this is not actionable for me.

I grow sceptical about email viability for any privacy related use cases.

I will keep this in mind and maybe one day CypherpunkPay will add asynchronous user communication with some modern p2p IM.

Meanwhile, user can bookmark the URL as a status / receipt page.
