### ISSUE TITLE
Unable to use SSL offloader (Haproxy)

### ISSUE THREAD

**Issue by Re4mstr** [CypherpunkPay/CypherpunkPay#20]
Using Haproxy with OPNsense against cypherpunkpay, but getting mixed content warnings (weird gui, blocked stylesheets) and 404 on /charge.

Any way to properly reverse proxy without using "built-in" caddy etc?

**Comment by CypherpunkDev** [comment]
Please try this (it's for nginx but I hope you will be able to translate to your reverse proxy):
https://cypherpunkpay.org/installation/troubleshooting

Let me know if successful!

**Comment by Re4mstr** [comment]
I have tried both Caddy and Nginx which both yielded the same results.
I serve a lot of locally hosted http content through the Haproxy setup, and never change any settings on the firewall/proxy.

I am not familiar with requests etc, but to me, it looks like http-content is force-requested by cypherpunkpay
![Capture](https://user-images.githubusercontent.com/15211713/150490924-e83aa954-69ae-4491-8c74-770d4fd23943.PNG)

**Comment by CypherpunkDev** [comment]
CypherpunkPay believes the request came as HTTP so it renders `http://` links.

Your Haproxy needs to set `X-Forwarded-Proto` header to inform downstream web servers that request came as `https://`. Here is how to do it:
https://cri.dev/posts/2020-05-26-Upgrade-HTTP-requests-with-X-Forwarded-Proto-Header-in-HAProxy/

Please also make sure you have this line in the `[server]` section in your `/etc/cypherpunkpay.conf` (the default):
`trusted_proxy_headers = x-forwarded-for x-forwarded-host x-forwarded-proto x-forwarded-port`

Please let me know if it helped!

**Comment by CypherpunkDev** [comment]
Alternatively, add `url_scheme = https` to the `[server]` section in your `/etc/cypherpunkpay.conf`.

This will force https in CypherpunkPay regardless of upstream protocol headers.

Let me know!

**Comment by Re4mstr** [comment]
> 

This solved it.

I wouldn't know if this'll cause any security implications, but everything works so far.
I'll get to test payments, but so far so good.

Thank you for this amazing software, and great support.

**Comment by CypherpunkDev** [comment]
> I wouldn't know if this'll cause any security implications, but everything works so far.

No security implications with `url_scheme = https`.

The only implication is that if you point your web browser directly to the local network address of your CypherpunkPay (like 192.168...) then it won't work because it will still force https. But you most likely won't ever need this.
