### ISSUE TITLE
Wallet address creation NOT associated with xpub wallet input in config file!

### ISSUE THREAD

**Issue by naturallaw777** [CypherpunkPay/CypherpunkPay#23]
Donations is generating wallet addresses not associated with mainnet xpub wallet in config file. I just sent off some bitcoin to a wallet that cypherpunkpay generated (thinking it was from my xpub) that is not associated with the mainnet xpub wallet saved in the config file.

**Comment by CypherpunkDev** [comment]
1) Do you use a P2WPKH wallet? CypherpunkPay works with native segwit and generates bech32 addresses.

2) Are you sure CypherpunkPay uses the exact config file you have in mind?

3) Have you restarted CypherpunkPay after the config change?

**Comment by CypherpunkDev** [comment]
@naturallaw777 any update on this?

**Comment by naturallaw777** [comment]
Hey! So sorry for the delay. It was MY mistake. I am sorry about that. I use sparrow wallet and I did not see the feature to "Refresh Wallet" and when I did it worked!!!  Thanks so much for making great software!

**Comment by CypherpunkDev** [comment]
No worries, thanks for your interest in CypherpunkPay. BTW Great wallet choice, Sparrow rulez.
