### ISSUE TITLE
NO_PUBKEY 88249242C907DBA0

### ISSUE THREAD

**Issue by markjr** [CypherpunkPay/CypherpunkPay#24]
Hi, trying to install on Deb 11, apt-get update failing:

`
Err:5 https://deb.cypherpunkpay.org/apt/debian bullseye InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 88249242C907DBA0
Reading package lists... Done
W: GPG error: https://deb.cypherpunkpay.org/apt/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 88249242C907DBA0
`

I've imported the GPG keys from the website as well but this one isn't there.

Can't find it on the keyservers...

`
gpg --keyserver keyserver.ubuntu.com --search-key 88249242C907DBA0
gpg: data source: http://162.213.33.8:11371
gpg: key "88249242C907DBA0" not found on keyserver
gpg: keyserver search failed: Not found
`

**Comment by CypherpunkDev** [comment]
Have you followed the quick start instructions precisely? https://cypherpunkpay.org/installation/quick-start/

Pasting from the quick start:

    # Add cypherpunkpay package signing key
    wget -qO - https://deb.cypherpunkpay.org/cypherpunkpay-package-signer.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/cypherpunkpay-archive-keyring.gpg 1> /dev/null

    # Add cypherpunkpay repository
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/cypherpunkpay-archive-keyring.gpg] https://deb.cypherpunkpay.org/apt/debian/ bullseye main' | sudo tee /etc/apt/sources.list.d/cypherpunkpay.list

Maybe you imported the key in a custom way that doesn't affect your apt-get?

Or maybe you missed the `signed-by` part when adding deb to your repos list?

Please let me know if it helped!

**Comment by markjr** [comment]
Hi, thanks for the reply. I did do both steps.

Somebody else here fixed it, saying

> It was the source file. Signing key location was not working.

I don't have further details on that at the moment but I think we can close this.
