### ISSUE TITLE
ERROR Job "update_price_tickers" raised exception

### ISSUE THREAD

**Issue by markjr** [CypherpunkPay/CypherpunkPay#25]
Hi folks, pretty much a clean install and now following these instructions....

https://cypherpunkpay.org/installation/bitcoin-wallet/

Now that I've added my zpub and switched to mainnet I'm just getting screen

> Try again in a couple seconds. We are initializing currency conversion rates and other stuff.

In the logs

`30]: 2022-03-02 16:35:53,132 ERROR Job "update_price_tickers" raised exception
30]: Traceback (most recent call last):
30]:   File "/opt/venvs/cypherpunkpay/lib/python3.9/site-packages/cypherpunkpay>
30]:     self.job()
30]:   File "/opt/venvs/cypherpunkpay/lib/python3.9/site-packages/cypherpunkpay>
30]:     lambda: self._app.price_tickers().update(),
30]:   File "/opt/venvs/cypherpunkpay/lib/python3.9/site-packages/cypherpunkpay>
30]:     self.update_fiats()
30]:   File "/opt/venvs/cypherpunkpay/lib/python3.9/site-packages/cypherpunkpay>
30]:     price_start_ix = xml.index(looking_for) + 12
30]: ValueError: substring not found
`

**Comment by CypherpunkDev** [comment]
Thanks for your bug report!

European Central Bank removed `RUB` from their official XML API at https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

This prevented CypherpunkPay from understanding currency conversion rates among supported fiats.

I am working on a fix.

**Comment by CypherpunkDev** [comment]
Fixed in the latest release.
