### ISSUE TITLE
Updating section "Add CypherpunkPay repository (deb.cypherpunkpay.org)" on cypherpunkpay.org

### ISSUE THREAD

**Issue by bitcoin-public-domain** [CypherpunkPay/CypherpunkPay#3]
Updating section: https://cypherpunkpay.org/installation/quick-start/#add-cypherpunkpay-repository-debcypherpunkpayorg

There is a major change in Debian and all Debian based systems including Ubuntu regarding adding repositories to apt: 

**Old method which listed on the website will not work:**
```
# Add cypherpunkpay package signing key
wget -qO - https://deb.cypherpunkpay.org/cypherpunkpay-package-signer.asc | sudo apt-key add -

# Add cypherpunkpay repository
echo 'deb [arch=amd64] https://deb.cypherpunkpay.org/apt/debian/ buster main' | sudo tee /etc/apt/sources.list.d/cypherpunkpay.list
```

Proposing to update to the following: 
```
# Add cypherpunkpay package signing key
curl https://deb.cypherpunkpay.org/cypherpunkpay-package-signer.asc | gpg --dearmor > /usr/share/keyrings/cypherpunkpay-archive-keyring.gpg

# Add cypherpunkpay repository
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/cypherpunkpay-archive-keyring.gpg] https://deb.cypherpunkpay.org/apt/debian/ buster main' | tee -a /etc/apt/sources.list.d/cypherpunkpay.list
```

Note that Debian 11 "bullseye" have been released, so probably you should also change from `https://deb.cypherpunkpay.org/apt/debian/ buster main` to `https://deb.cypherpunkpay.org/apt/debian/ bullseye main`

**Comment by CypherpunkDev** [comment]
This is very helpful, thanks!

Should I only do it for Debian 11 and Ubuntu 22.04?

Or maybe it's safe to apply the change down to Ubuntu 18.04 and Debian 10 as well?

**Comment by CypherpunkDev** [comment]
Added Debian 11 and replaced apt-key as you suggested. Thanks!
