### ISSUE TITLE
Some questions and feedback

### ISSUE THREAD

**Issue by khand100** [CypherpunkPay/CypherpunkPay#4]
Hi,
thanks for this awesome project. I really like the simpler (single daemon) approach, because I was getting really annoyed of btcpayserver forcing me to use docker.

I already switched to CypherpunkPay but still have some questions.

1. Is it possible to activate callbacks for all final states. It looks like for `expired` and `cancelled` payments the callback is not executed.

2. Is it possible to disable the `/cyberpunkpay/` subpath? I would prefer clean urls with only a subdomain e.g. https://pay.example.com/donations

3. Have you considered allowing custom css theming, or at least a dark theme? I think bulma still does not have an automatic dark mode (https://github.com/jgthms/bulma/issues/2342) but maybe it could be added with this https://github.com/jloh/bulma-prefers-dark?  
In the meantime I will probably modify the main.css file myself.

4. Could you add an optional item description field like btcpayserver has? This would for example be shown during the checkout and especially on the last payment waiting screen, so customers are reassured for what they are currently paying. With btcoayserver I also used this to display the fiat price. [Here](https://imgur.com/a/SkZgTcd) is a mock with a simple `<h2 class="subtitle">item description</h2>` under the title.

5. How ready is monero? I saw it in the code multiple times, but it is not mentioned in the docs. Can I already use it? How is it configured?

Sorry, I know this is not an issue but still seamed to be the best way to contact you. When the community is bigger maybe [GitHub Discussions](https://docs.github.com/en/discussions) can be the place for these type of questions.

**Comment by CypherpunkDev** [comment]
Thanks for your feedback and excellent questions!

1. There are no callbacks other than **payment_completed** (the happy path). Following your feedback I am now planning to address this shortcoming.

2. Unfortunately the path prefix is currently hardcoded as `/cypherpunkpay`. I agree it should be possible to disable the prefix. I hope to improve this but it may not necessarily be a top priority.

3. Dark theme would be cool and yes I would like to have it one day. However, custom CSS overrides are very likely to break with subsequent releases. I definitely do not aim at backwards compatibility for the HTML/CSS layer.

4. Yes, this is definitely desirable and a priority task.

5. Monero is not implemented. Thanks for expressing your interest in using CypherpunkPay with Monero! I am very keen to attempt adding Monero. I am currently working on adding minimal Lightning Network support. Depending on how things go, Monero may be the next big thing in the pipeline.

**Comment by CypherpunkDev** [comment]
I converted actionable items into separate issues. Feel free to reopen this issue or continue on specific topics.

**Comment by khand100** [comment]
Thanks for the answers.

I can understand that you do not want to support custom css, I would neither 😄. I was thinking more of an option to configure a path to a css file that then is injected into all pages. Maybe with a warning that users are responsible themselves to check if their css breaks stuff.

Great to hear that you are motivated to add the item descriptions and monero support.

**Comment by CypherpunkDev** [comment]
Items 1., 2. and 4. are now done and released.

**Comment by khand100** [comment]
Awesome, thanks again for this great project.

The payment_failed_notification_url works as expected 👍🏻
