### ISSUE TITLE
Add option to disable tor for merchant callback url

### ISSUE THREAD

**Issue by khand100** [CypherpunkPay/CypherpunkPay#9]
Hi,
it looks like I need an option to disable tor for the merchant callback url.
On production the callback url is behind cloudflare and it looks like the requests sometimes get blocked when they are routed over tor.
I can not use the `privacy_context = 'local_network'` bypass because the request has to be made with a valid host header to reach the correct backend.

Took me some time to debug this. I think logging non 200 http response codes for the callback request would also be nice (for easier debugging).

**Comment by CypherpunkDev** [comment]
Thanks for bringing this up. I agree it is desirable.
